root = "."
tmp_dir = "bin"

[build]
	cmd = "make build"
	delay = 0
	exclude_dir = ["static", "node_modules"]
	exclude_regex = []
	exclude_unchanged = false
	follow_symlink = false
	include_ext = ["go", "templ", "css", "js"]
	kill_delay = "0s"
	log = "tmp/air-build-errors.log"
	send_interrupt = false
	stop_on_error = true

[color]
	build = "yellow"
	main = "magenta"
	runner = "green"
	watcher = "cyan"

[log]
	time = true

[misc]
	clean_on_exit = true
