services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - "db"
    env_file:
      - ".env"
    ports:
      - "8081:8080"
    networks:
      - "dev"
    develop:
      watch:
        - action: "rebuild"
          path: "."
          files:
            - "./**/*.go"
            - "./go.mod"
            - "./go.sum"

  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    restart: "always"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - "dev"

  pgadmin:
    image: "docker.io/dpage/pgadmin4:8.4"
    depends_on:
      - "db"
    env_file:
      - ".env"
    ports:
      - "5050:80"
    networks:
      - "dev"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "256M"

networks:
  dev:
    driver: "bridge"
